In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [14]:
x_train.shapepe

(60000, 28, 28)

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.18902518, -0.32353258, -0.3557536 ,  0.22818288,  0.00706891,
         0.81538117,  0.08564009,  0.7143751 , -0.3886965 , -0.3071569 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07311614, 0.06391421, 0.06188766, 0.11096971, 0.08895612,
        0.19962797, 0.09622742, 0.1804492 , 0.05988211, 0.06496947]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

1.6112999

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
)

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3008 - accuracy: 0.9121
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1409 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1078 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0863 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0749 - accuracy: 0.9768


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0765 - accuracy: 0.9785 - 391ms/epoch - 1ms/step


[0.07645248621702194, 0.9785000085830688]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.93043153e-08, 3.74001452e-09, 1.33176400e-05, 3.94135823e-05,
        3.12978976e-09, 6.76545184e-08, 2.66246313e-12, 9.99933481e-01,
        1.41724854e-07, 1.34111642e-05],
       [1.12857423e-09, 2.59994522e-06, 9.99995589e-01, 1.77224422e-06,
        1.94573560e-17, 3.67050852e-08, 3.52173117e-11, 1.67074622e-12,
        3.32582561e-09, 1.33064336e-16],
       [5.48466687e-07, 9.98822272e-01, 3.76587013e-05, 6.26793235e-06,
        2.51364304e-06, 2.75841217e-06, 6.40460121e-06, 1.09593081e-03,
        2.55971354e-05, 5.50448185e-08],
       [9.99931455e-01, 1.25742119e-08, 3.24596112e-05, 4.75307388e-07,
        2.62594949e-06, 2.18399055e-06, 1.92049974e-05, 1.53755263e-06,
        2.69566569e-09, 1.01656315e-05],
       [7.74059117e-06, 2.85037660e-09, 1.99745568e-06, 1.13765353e-08,
        9.99032378e-01, 2.61680650e-08, 2.15156410e-06, 2.83266651e-04,
        2.45054252e-08, 6.72355120e-04]], dtype=float32)>