In [ ]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.139171  ,  0.4025756 , -0.00263986,  0.00476119,  0.66831684,
        -0.26758438,  0.08163109, -0.0691018 ,  0.5131865 ,  0.12971458]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09427845, 0.12268957, 0.08181347, 0.08242122, 0.16003597,
        0.06277126, 0.0890068 , 0.07655274, 0.13703938, 0.09339113]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.7682579

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
)

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3037 - accuracy: 0.9114
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1455 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1092 - accuracy: 0.9665
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0890 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0780 - accuracy: 0.9761


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0757 - accuracy: 0.9763 - 309ms/epoch - 988us/step


[0.07565619796514511, 0.9763000011444092]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.08232410e-08, 6.85834145e-09, 9.04612898e-06, 4.90742852e-04,
        3.33640711e-12, 8.00246625e-08, 7.79778759e-12, 9.99498367e-01,
        4.06886585e-07, 1.26671387e-06],
       [5.94245790e-08, 3.66561762e-05, 9.99961376e-01, 2.70625094e-07,
        1.19380125e-15, 1.74832780e-06, 1.84357916e-08, 3.92208103e-15,
        3.28381589e-08, 5.45047948e-14],
       [1.14663908e-06, 9.99160290e-01, 1.08144035e-04, 1.43027783e-05,
        6.98764634e-05, 4.53963639e-06, 1.64767207e-05, 5.35859261e-04,
        8.92552998e-05, 1.29277069e-07],
       [9.98578906e-01, 1.14640786e-08, 8.73773417e-04, 4.97878636e-06,
        1.40337522e-06, 1.83361266e-07, 5.36753156e-04, 9.13113141e-08,
        3.10458006e-07, 3.55929797e-06],
       [8.69943251e-05, 6.00629022e-08, 6.61996228e-06, 2.59545345e-07,
        9.97043073e-01, 4.44864781e-06, 9.39469246e-05, 6.92831190e-06,
        1.53242706e-06, 2.75621563e-03]], dtype=float32)>